---
- name: Устанавливаем Node Exporter
  apt:
    name: prometheus-node-exporter
    state: present
    update_cache: yes
    cache_valid_time: 3600
  register: apt_node_exporter
  until: apt_node_exporter is succeeded
  retries: 5
  delay: 5

- name: Запускаем и добавляем в автозагрузку
  systemd:
    name: prometheus-node-exporter
    state: started
    enabled: yes
