[control]
ctrl ansible_connection=local ansible_user=student

[web]
node1 ansible_user=student
node2 ansible_user=student

[monitoring]
mon ansible_user=student

[all:vars]
ansible_python_interpreter=/usr/bin/python3
